apiVersion: v2
name: ingress-doperator-chart
description: A Kubernetes operator that translates Ingress resources to Gateway API resources
type: application
version: v0.0.1
appVersion: v0.0.1
keywords:
  - ingress
  - gateway-api
  - operator
maintainers:
  - name: Gregor Pogacnik
home: https://github.com/fiksn/ingress-doperator
